# Файл docker-compose.yml

# Перечень volume
volumes:
  pg_data:
  static:

# Перечень контейнеров
services:

  # Имя и описание первого контейнера; имя выбирает разработчик.
  # Это контейнер БД
  db:
    container_name: taski-db
    # Из какого образа запустить контейнер:
    image: postgres:13.10
    # Файл (или список файлов) с переменными окружения
    env_file: .env
    # Какой volume подключить для этого контейнера
    volumes:
      - pg_data:/var/lib/postgresql/data

  # Имя и описание контейнера с бэкендом
  backend:
    container_name: taski-backend
    # Из какого Dockerfile собирать образ для этого контейнера:
    image: wallery/taski_backend:latest
    env_file: .env
    # Какие контейнеры нужно запустить до старта этого контейнера:
    depends_on:
      - db
    volumes:
      - static:/backend_static

  # Имя третьего контейнера. Это контейнер с фронтендом
  frontend:
    container_name: taski-frontend
    env_file: .env
    image: wallery/taski_frontend:latest
    volumes:
      - static:/frontend_static
    command:
      cp -r /app/build/. /frontend_static/

  gateway:
    container_name: taski-gateway
    # Сбилдить и запустить образ,
    # описанный в Dockerfile в папке gateway
    image: wallery/taski_gateway:latest
    # Ключ ports устанавливает
    # перенаправление всех запросов с порта 8000 хоста
    # на порт 80 контейнера
    depends_on:
      - backend
    volumes:
      - static:/staticfiles
    ports:
      - 8000:80

